spring:
  application:
    name: channel-integration

hotel-mapping:
  sync:
    fixed-delay-ms: 86400000

supplier:
  a:
    base-url: http://localhost:9090
    api-key: dummy-key-a
    connect-timeout-ms: 1000
    response-timeout-ms: 4000
  b:
    base-url: http://localhost:9090
    api-key: dummy-key-b
    connect-timeout-ms: 1000
    response-timeout-ms: 4000
